spring:
  application:
    name: service-a
server:
  port: 10101
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    metadata-map:
      versions: 1,2